# Generated by Django 2.2.4 on 2019-08-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default=None, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image1', models.ImageField(default=None, upload_to='images')),
                ('image2', models.ImageField(default=None, upload_to='images')),
                ('image3', models.ImageField(default=None, upload_to='images')),
                ('image4', models.ImageField(default=None, upload_to='images')),
                ('image5', models.ImageField(default=None, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Topper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('className', models.CharField(max_length=20)),
                ('marks', models.CharField(max_length=10)),
            ],
        ),
    ]
