# Generated by Django 2.2.4 on 2019-09-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20190909_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image1',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image3',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image4',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image5',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
    ]
