# Generated by Django 2.2.4 on 2019-09-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('title', models.CharField(blank=True, default='Sample', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title',
            field=models.CharField(blank=True, default='Sample', max_length=50),
        ),
    ]
